### ISSUE TITLE
CMake warning about deprecated policy related to RPATH

### ISSUE THREAD

**Issue by scfc** [ledger/ledger#1721] opened 2019-01-15 02:29 UTC
CMake 3.11.2 warns:

    CMake Deprecation Warning at CMakeLists.txt:4 (cmake_policy):
      The OLD behavior for policy CMP0042 will be removed from a future version
      of CMake.
    
      The cmake-policies(7) manual explains that the OLD behaviors of all
      policies are deprecated and that a policy should be set to OLD only under
      specific short-term circumstances.  Projects should be ported to the NEW
      behavior and not rely on setting a policy to OLD.

The triggering code was added in commit ac5fd3afd3826a9b0fadcb270900cf42c5ee6e39 with the intention:

    Set CMake policy CMP0042
    
    to remove the warning below when running cmake.
    In the long run changing the CMake rules to set MACOSX_RPATH
    might be the better option.
    
      CMake Warning (dev):
        Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
        --help-policy CMP0042" for policy details.  Use the cmake_policy
        command to set the policy and suppress this warning.
        MACOSX_RPATH is not specified for the following targets:
    
         libledger
    
      This warning is for project developers.  Use -Wno-dev to suppress it.

[Policy CMP0042](https://cmake.org/cmake/help/latest/policy/CMP0042.html) is (AFAIUI) irrelevant to Linux where CMake 3.11.2 seems to do Almost The Right Thing™ by default (set `RPATH` for `ledger` to source directory when building and testing and to (for example) `/usr/lib64` when installing; some/most distributions will want to clear that field when installing by setting `CMAKE_SKIP_INSTALL_RPATH`).  So my instinct would be to remove the four lines from `CMakeLists.txt` and the one line from `src/CMakeLists.txt` that relate to `RPATH`.

But I do not know how this plays out under macOS.  I assume the default there is reasonable as well, but I have no way of testing this.

**Comment by tbm** [comment] 2019-12-07 09:26
@afh @xnox @scfc any comments on this?

**Comment by xnox** [comment] 2019-12-12 11:59
https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/RPATH-handling

**Comment by tbm** [comment] 2020-03-27 07:20
@scfc ... ?

**Comment by tbm** [comment] 2020-05-08 04:41
@xnox any help?

**Comment by tbm** [comment] 2021-01-17 02:22
@q3aiml any chance you could look at this issue?

**Comment by tbm** [comment] 2021-02-02 10:56
@scfc @q3aiml can someone submit a patch for this?  It sounds like this needs to be fixed.

**Comment by Rahix** [comment] 2021-08-04 14:14
The lines from ac5fd3afd3826a9b0fadcb270900cf42c5ee6e39 were already dropped in 6d4cd58cd4b1b2f3906889009da7b71931645e93 so I think this is already resolved anyway?

**Comment by Rahix** [comment] 2021-08-04 14:15
It looks like @xnox has taken care of this issue in #1839 already.  @tbm I think you can close this issue.

Just to make sure, I was not able to reproduce the warning in the OP anymore, either.

**Closed** 2022-05-05 23:25 UTC
