### ISSUE TITLE
Documentation link not working

### ISSUE THREAD

**Issue by valankar** [ledger/ledger#2214] opened 2023-03-16 17:54 UTC
On this page:

https://www.ledger-cli.org/docs.html

Clicking on the manual gives an error:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>7XT2TS91RMMYRVNQ</RequestId>
<HostId>tjWmpmKO/OMSj0kB4Id9JCneLeCd+zoZWyMwRUYWDDi93k2Aj+rhPLvkPwQUEFmmunvYDMM4hME=</HostId>
</Error>
```

**Comment by afh** [comment] 2023-03-16 18:11
Closing as duplicate of #2211

**Closed by afh** 2023-03-16 18:11 UTC

**Comment by afh** [comment] 2023-03-24 10:06
With the migration being completed (see ledger/ledger.github.io#46 for details) this has been resolved. If there are other issues please report them on [ledger/ledger.github.io](https://github.com/ledger/ledger.github.io/issues/new/choose). Thanks for raising this, @valankar.
