### ISSUE TITLE
Documentation link is broken, it redirects to unauthorized page.

### ISSUE THREAD

**Issue by AsifMushtaq** [ledger/ledger#2221] opened 2023-03-22 09:59 UTC
https://www.ledger-cli.org/doc/ledger3.html
returns

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>T01D8VES1B7SPD3R</RequestId>
<HostId>r6IkySijMRLgZXMM+VJuOR3tpEnfGFwYmeWVV29JlNcCs/d8AzEhWOngO0GnuRXru5KOkZyGIwE=</HostId>
</Error>
```

**Comment by afh** [comment] 2023-03-22 10:45
Closing as duplicate of #2211

**Closed by afh** 2023-03-22 10:45 UTC

**Comment by afh** [comment] 2023-03-24 10:05
With the migration being completed (see ledger/ledger.github.io#46 for details) this has been resolved. If there are other issues please report them on [ledger/ledger.github.io](https://github.com/ledger/ledger.github.io/issues/new/choose). Thanks for raising this, @AsifMushtaq.
