### ISSUE TITLE
Instructions for installing with Python

### ISSUE THREAD

**Issue by alberto56** [ledger/ledger#1886] opened 2020-04-17 14:07 UTC
I'm trying to install Ledger with Python support in the Docker version at https://github.com/dcycle/docker-ledger/issues/9

Python is installed, but I'm getting "Python support is missing":

```
While parsing file "/data/python.dat", line 4:
Error: 'python' directive seen, but Python support is missing
While parsing file "/data/python.dat", line 16:
While evaluating value expression:
  check_path(value)
  ^^^^^^^^^^^^^^^^^
```

My Dockerfile [currently looks like this](https://github.com/dcycle/docker-ledger/blob/dev/9/Dockerfile), any guidance on how I can install Python support would be appreciated, thanks!

**Comment by tbm** [comment] 2020-05-08 04:44
Maybe related to #1893?

**Comment by ngleb** [comment] 2020-05-08 05:50
I think that in Dockerfile they install ledger from Alpine repository, which builds ledger without Python support.

https://pkgs.alpinelinux.org/contents?branch=edge&name=ledger&arch=x86_64&repo=testing
https://build.alpinelinux.org/buildlogs/build-edge-x86_64/testing/ledger/ledger-3.1.3-r4.log

**Comment by afh** [comment] 2023-04-16 20:17
Closing as invalid as the issue is with a downstream distribution.

**Closed by afh** 2023-04-16 20:17 UTC
Labels: invalid, python
