### ISSUE TITLE
Issue with expression evaluation

### ISSUE THREAD

**Issue by blatte** [ledger/ledger#1894] opened 2020-05-06 08:20 UTC
I have automated transactions formated like so:

```
= /Expenses:Transportation/ and not expr "has_tag(/NOTAX/)"
         Expenses:Tax                     0.2
         $account                        -0.2
```

The idea is for the transaction to apply unless the account has the tag NOTAX.

This used to work but it now does not apply for any transcation at all.

**Comment by tbm** [comment] 2020-05-06 08:32
Confirmed to work with 3.1.2. Does not work with 3.2.0.

**Comment by tbm** [comment] 2020-05-06 09:29
This was introduced by:

commit 49b07a1c19489547b859d61fbc5c240aff224dda (refs/bisect/bad)
Author: John Wiegley <john@dfinity.org>
Date:   Tue Sep 17 16:54:58 2019 -0700

    Correction to the way parens are parsed in query expressions

@jwiegley can you take a look?

**Comment by tbm** [comment] 2020-05-06 09:30
Complete test case:

```
= /Expenses:Transportation/ and not expr "has_tag(/NOTAX/)"
         Expenses:Tax                     0.2
         $account                        -0.2

2020-05-06 * Test
    Expenses:Transportation            200.00 EUR
    Assets:Bank                       -200.00 EUR
```

Correct output:

```
         -200.00 EUR  Assets:Bank
          200.00 EUR  Expenses
           40.00 EUR    Tax
          160.00 EUR    Transportation
--------------------
                   0
```

**Comment by jwiegley** [comment] 2020-05-08 04:25
The query parser is I'm really not very happy with.

I confirm the bug, and have reverted my change.

**Comment by Rahix** [comment] 2020-05-08 08:14
I think I have also hit this bug with the following automatic transaction:

```text
= ^Expenses and %split-half and expr "any(account =~ /^A:Assets|^A:Expenses:Cash/ and R)"
    [A:Assets:Split]              (amount / 2)
    [B:Assets:Split]              (-amount / 2)
```

Using the latest version from git (869302ae9ce3) fixes the issue.

**Comment by jwiegley** [comment] 2020-05-11 17:38
It's good to have more examples, thank you. Before I make any future change to this code (to fix the issue I had run into), I'll build up a battery of regression tests to ensure we don't break people's Ledger files.

**Comment by tbm** [comment] 2020-05-12 02:44
@jwiegley I'm not sure if this is *strictly* related since I don't know what you were trying to fix, but when you look into this please also consider issue #872 and issue #1185.  They are examples of things not properly parsed today.

**Comment by Rahix** [comment] 2020-05-12 15:11
Now that the offending change has been reverted, would it be possible to issue a point release with this fix included?  I feel like a bug like this, which silently reports wrong numbers for peoples transactions, could be quite dangerous ...

**Comment by tbm** [comment] 2020-05-13 00:18
@Rahix I am planning on making a point release but I wanted to wait for a fix for another regression: issue #1895

Do you think the point release can wait until next week (assuming @jwiegley has time to fix #1895 on the weekend) or should I make 2 point releases (one now and one for the other fix).

**Comment by Rahix** [comment] 2020-05-13 08:38
Well, you probably know better than me how long it takes for a ledger release to get into the distro repositories.  Looking at [this overview](https://pkgs.org/search/?q=%2Fusr%2Fbin%2Fledger), only `ArchLinux`, `Debian Sid`, and `openSUSE Tumbleweed` ship 3.2.0 already so it might not be too bad.  Maybe add a disclaimer on the [release page](https://github.com/ledger/ledger/releases/tag/v3.2.0) linking to the two issues and instructing people to wait for the fixes?

**Comment by jwiegley** [comment] 2020-05-16 01:09
I'll work on `--invert` this weekend, and we should be able to release on Monday.

**Comment by tbm** [comment] 2020-05-18 05:26
I opened a new ticket for @jwiegley to keep track of the parser rework: #1911

**Comment by tbm** [comment] 2020-05-18 05:27
This was fixed in:

commit 869302ae9ce303b532fa4700f78d208c3bd89310
Author: John Wiegley <johnw@newartisans.com>
Date:   Thu May 7 21:22:20 2020 -0700

    Revert "Correction to the way parens are parsed in query expressions"
    
    This reverts commit 49b07a1c19489547b859d61fbc5c240aff224dda.

**Closed by tbm** 2020-05-18 05:27 UTC
Labels: P1, bug
