### ISSUE TITLE
Documentation links appear down

### ISSUE THREAD

**Issue by mittenchops** [ledger/ledger#2215] opened 2023-03-20 02:37 UTC
The documentation links on...
![image](https://user-images.githubusercontent.com/1584795/226233378-4788bec1-e99d-4f2c-9155-7435b225b8f4.png)

such as  https://www.ledger-cli.org/doc/ledger3.html

produce
![image](https://user-images.githubusercontent.com/1584795/226233781-eab00b88-d274-489e-b732-b65231937fd1.png)

Where I have redacted the requestId and HostId.

**Comment by afh** [comment] 2023-03-20 07:07
Closing as duplicate of #2211

**Closed by afh** 2023-03-20 07:08 UTC
