### ISSUE TITLE
Python tests fail, rather than being skipped, when ledger is built without Python support

### ISSUE THREAD

**Issue by riastradh** [ledger/ledger#2331] opened 2024-02-21 22:32 UTC
After cmake, make, and make check, test/Testing/Temporary/LastTest.log contains:

```
FAILURE in error output from /home/riastradh/misc/ledger/master/test/baseline/dir-python_py.test:
--
$ledger -f "/home/riastradh/misc/ledger/master/test/baseline/dir-python_py.test" reg

--
  @@ -1,2 +1,12 @@
  
  -Warning: "/home/riastradh/misc/ledger/master/test/baseline/dir-python_py.test", line 18: Metadata check failed for (PATH: test/baseline/feat-import_noexist.test): check_path(value)
  
  -Warning: "/home/riastradh/misc/ledger/master/test/baseline/dir-python_py.test", line 18: Metadata check failed for (PATH: test/baseline/feat-import_noexist.test): ((os.path).isfile(value))
  
  +While parsing file "/home/riastradh/misc/ledger/master/test/baseline/dir-python_py.test", line 1:
  
  +Error: 'python' directive seen, but Python support is missing
```

**Comment by afh** [comment] 2024-02-21 23:07
@riastradh this looks like a duplicate of #2324, would you agree?
Also you could apply the changes from #2325 locally and try once more, please?

**Closed as completed** 2024-02-21 23:10 UTC
Labels: duplicate
