### ISSUE TITLE
Last character of ledger file is ignored if not a newline causing 'Transaction does not balance'

### ISSUE THREAD

**Issue by ralfebert** [ledger/ledger#1887] opened 2020-04-19 08:48 UTC
Using `Ledger 3.1.3-20190331` via homebrew on OS X, a super-straightforward transaction that should balance is reported as 'Transaction does not balance'

When running `ledger --args-only -f example.txt print`:

with the following file:

```
2020/02/01 * Example Payee
    Example                         $ 12.55
    Assets:Checking                 $ -12.55
```

I am getting:

```
While parsing file "example.txt", line 3:
While balancing transaction from "example.txt", lines 1-3:
> 2020/02/01 * Example Payee
>     Example                         $ 12.55
>     Assets:Checking                 $ -12.55
Unbalanced remainder is:
              $ 0.05
Amount to balance against:
             $ 12.55
Error: Transaction does not balance
```

It works when I change the amount to '12.50' or remove the amount for 'Assets:Checking'. But this transaction should balance or do I miss something obvious here? I suspected it's related to my German locale / using '--decimal-comma' which I usually use, but it happens without this option as well.

**Comment by ralfebert** [comment] 2020-04-19 09:05
Tested the same on a Debian/ledger 3.1.2-20190205, there it works without problems. So its likely related to macOS / system locale.

**Comment by ralfebert** [comment] 2020-04-19 09:49
Found it: it's the newline at the end of the file - if it's missing, the last digit is ignored.

**Comment by tbm** [comment] 2020-04-19 12:14
> Found it: it's the newline at the end of the file - if it's missing, the last digit is ignored.

Yes, you diagnosed the issue already. This is known, e.g. issue #516, #1871, #624. (I should close some of those)

**Comment by tbm** [comment] 2020-04-19 12:14
Closing as a duplicate of issue #516, #1871, #624

**Closed by tbm** 2020-04-19 12:14 UTC
Labels: duplicate
