### ISSUE TITLE
commodity alias does not work with `EUR`

### ISSUE THREAD

**Issue by rynr** [ledger/ledger#2138] opened 2022-10-30 15:01 UTC
I found #1678, but it seems to be something different, though the error message is the same.

See the following to reproduce:
```sh
$ ledger --version | grep Ledger
Ledger 3.2.1-20200518, the command-line accounting tool
$ cat usd.ledger
commodity $
  alias USD
$ ledger -f usd.ledger bal
$ cat eur.ledger 
commodity €
  alias EUR
$ ledger -f eur.ledger bal
While parsing file "eur.ledger", line 2:
Error: Assertion failed in "/build/ledger-pkKFq2/ledger-3.2.1/src/pool.cc", line 110:ledger::commodity_t* ledger::commodity_pool_t::alias(const string&, ledger::commodity_t&): result.second
$ 
```

I can define a commodity with the alias `USD`, but not with the alias `EUR`.  
Am I missing something here?

**Comment by tbm** [comment] 2022-10-31 01:49
I can't reproduce this.  Do you have a UTF-8 locale?

**Comment by rynr** [comment] 2022-10-31 07:31
My environment variables:
```
LANG=en_US.UTF-8
LANGUAGE=en_US:en
```
Are others relevant too?

**Comment by tbm** [comment] 2022-10-31 09:50
I was just guessing.  I don't know.  I can't reproduce the issue.

**Comment by afh** [comment] 2022-11-03 07:07
I'm also unable to reproduce this with the given instructions.

@rynr Can you provide the output of the `locale` command, please? `LC_CTYPE`, LC_NUMERIC`, and `LC_MONETARY` could be relevant…
```
% locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by spaette** [comment] 2023-01-08 16:19
> I can't reproduce this.

I'm also unable to reproduce this.

Running a UTF-8 locale however doesn't appear to be relevant.

I would suggest closing.

```
$ ledger --version | sed 1q
Ledger 3.2.1-20200518, the command-line accounting tool
$ 
```

konsole

```
$ echo $LANG
en_US
$ 
```

uxterm

```
$ echo $LANG
en_US.utf8
$ 
```

**Comment by tbm** [comment] 2023-01-09 00:22
@rynr do you still see this issue?

**Comment by spaette** [comment] 2023-01-09 15:07
This is output by `cmake` irrespective of whether or not one is running a UTF-8 locale.

`-- Performing Test BOOST_REGEX_UNICODE_RUNS - Failed`

konsole

```
$ echo $LANG
en_US
$ 
```

`make check`

```
94% tests passed, 25 tests failed out of 385

          1 - DocTestsTest_ledger3 (Failed)
         15 - BaselineTest_cmd-accounts (Failed)
         53 - BaselineTest_feat-convert-with-directives (Failed)
        101 - BaselineTest_opt-decimal-comma (Failed)
        131 - BaselineTest_opt-init-file (Failed)
        186 - BaselineTest_opt-rich-data (Failed)
        225 - RegressTest_1050 (Failed)
        227 - RegressTest_1057 (Failed)
        231 - RegressTest_1102 (Failed)
        232 - RegressTest_1106 (Failed)
        240 - RegressTest_1187_1 (Failed)
        241 - RegressTest_1187_2 (Failed)
        244 - RegressTest_1187_5 (Failed)
        265 - RegressTest_1D275740 (Failed)
        266 - RegressTest_1E192DF6 (Failed)
        281 - RegressTest_4509F714 (Failed)
        296 - RegressTest_5FBF2ED8 (Failed)
        313 - RegressTest_727B2DF8 (Failed)
        343 - RegressTest_AA2FF2B (Failed)
        349 - RegressTest_BF3C1F82-2 (Failed)
        354 - RegressTest_C523E23F (Failed)
        357 - RegressTest_CAE63F5C-a (Failed)
        367 - RegressTest_DB490507 (Failed)
        368 - RegressTest_DDB54BB8 (Failed)
        379 - RegressTest_FDFBA165 (Failed)
```
uxterm

```
$ echo $LANG
en_US.utf8
$ 
```

`make check`

```
99% tests passed, 1 tests failed out of 385

349 - RegressTest_BF3C1F82-2 (Failed)
```

**Comment by rynr** [comment] 2023-01-09 15:46
I did run it with `strace`. It loads a `~/.pricedb`, which contains:
```
P 2019-09-08 20:00:00 DTE 15.074 EUR
P 2019-09-08 20:00:00 FRE 44.620 EUR
P 2021-11-19 22:26:29 DTE 16.466 EUR
P 2021-11-19 22:26:29 FRE 35.690 EUR
P 2021-11-21 13:07:11 BTC 52074.9851 EUR
P 2022-10-30 15:30:00 BTC 20785.73 EUR
P 2022-10-30 15:30:00 DTE 19.28 EUR
P 2022-10-30 15:30:00 FRE 22.44 EUR
```
I removed that file, now I don't have any error.

**Comment by tbm** [comment] 2023-01-10 01:29
Great!  So we have a reduced test case now:

```
P 2019-09-08 20:00:00 DTE 15.074 EUR

commodity €
  alias EUR
```

Which triggers:

```
Error: Assertion failed in "src/pool.cc", line 110:ledger::commodity_t* ledger::commodity_pool_t::alias(const string&, ledger::commodity_t&): result.second
```

**Comment by tbm** [comment] 2023-01-10 01:31
So this is the same as issue #1678

This comment has a good explanation:

https://github.com/ledger/ledger/issues/1678#issuecomment-466655785

**Comment by spaette** [comment] 2023-01-10 13:58
unrelated but regarding `#1678` this renders in UXTerm

`perl -e 'no warnings "utf8"; print "\x{20AC}\n"'`

but not this

`perl -e 'no warnings "utf8"; print "\x{20BD}\n"'`

**Closed** 2023-04-25 17:35 UTC
Labels: bug, duplicate
