### ISSUE TITLE
BaselineTest_opt-lots fails (macos)

### ISSUE THREAD

**Issue by tko** [ledger/ledger#1747] opened 2019-01-23 17:32 UTC
macOS High Sierra 10.13.6 with up-to-date homebrew

Observed as part of `make check` and reproducable with `ctest --output-on-failure -R opt-lots`

```
$ledger -f "/Users/tko/Projects/ledger/test/baseline/opt-lots.test" reg -F '%(justify(scrub(total_expr), 80, 80, true))\n' --lots --date-format %Y/%m/%d
--
  @@ -70,8 +70,8 @@
                                                                             -1.25G
                                     "Plans: Wildthorn Mail" 1 {1.25G} [2006/03/14]
                                                                             -1.25G
  -                                  "Plans: Wildthorn Mail" 1 {1.25G} [2006/03/14]
                                                  "Plans: Wildthorn Mail" 1 {1.25G}
  +                                  "Plans: Wildthorn Mail" 1 {1.25G} [2006/03/14]
                                                                             -1.25G
                                     "Plans: Wildthorn Mail" 1 {1.25G} [2006/03/14]
                                     "Plans: Wildthorn Mail" 1 {1.25G} [2006/03/14]
```
followed by very many similar chunks where the lines are getting reordered.

**Comment by tko** [comment] 2019-01-23 19:42
@tbm a little, but I wouldn't count on me. I tried bisecting but two runs point me to two different commits d4ede603c9442bca4675d8cde2759636d3d87008 and d1a22677c94f604f47fa637adda850e1df745f96, and both look nonsense to me. I'll try once more but other than git bisect I don't even know how to start.

**Comment by tbm** [comment] 2019-01-23 19:44
Such issues are (in my limited experience) usually compiler or boost issues (i.e. ledger does something not quite right but it only shows up later when the toolchain changes).  So I would suspect you'd get the same result if you compiler an older ledger.  But who knows....

**Comment by tbm** [comment] 2019-01-23 19:45
(or the strange results you get because it's not 100% deterministic)

**Comment by tko** [comment] 2019-01-23 19:56
I have

boost: homebrew 1.68.0_1
c++: Apple LLVM version 10.0.0 (clang-1000.11.45.5)

but not really in a position to start bisecting either of those.

**Comment by tbm** [comment] 2019-01-28 18:07
@jwiegley can you reproduce this?

**Comment by tbm** [comment] 2019-01-28 21:46
@mbudde? ;)

**Comment by mbudde** [comment] 2019-01-28 21:54
I think I'll have a hard time debugging this without a Mac :man_shrugging:

**Comment by jwiegley** [comment] 2019-01-30 06:03
This doesn't reproduce for me.

**Comment by jwiegley** [comment] 2019-01-30 06:05
I'll note here that the correct output is being displayed, it's just that the sorting is off. This is established by `commodity_t::compare_by_commodity::operator()`, so I wonder what it's being sensitive to here...

**Comment by jwiegley** [comment] 2019-01-30 19:45
The test `BaselineTest_cmd-pricedb` also intermittently fails.

**Comment by tbm** [comment] 2019-03-16 07:51
@tko this should be fixed with the changes @jwiegley made today. Can you please check.

**Comment by tko** [comment] 2019-03-17 13:22
@tbm worksforme

I can't make `BaselineTest_opt-lots` trip anymore, but with (very many) repeated test runs `BaselineTest_cmd-pricedb` eventually fails.

**Comment by tbm** [comment] 2019-03-27 12:36
@tko 

> but with (very many) repeated test runs BaselineTest_cmd-pricedb eventually fails.

If it's repeatable, I suggest you open a new ticket.

**Comment by jwiegley** [comment] 2019-03-28 04:23
Agreed, it's a different bug.

**Closed by jwiegley** 2019-03-28 04:23 UTC
Labels: bug
