### ISSUE TITLE
Various issues with last character of file, e.g., Error: Transaction does not balance

### ISSUE THREAD

**Issue by bradyt** [ledger/ledger#1871] opened 2020-03-20 03:42 UTC
If I have a file with the following contents,

```
1970-01-01 example
 A  1
 B
```

Then I see this:

```
$ ledger -f example.dat bal
While parsing file "/tmp/example.dat", line 3:
While balancing transaction from "/tmp/example.dat", lines 1-3:
> 1970-01-01 example
>  A  1
>  B
Unbalanced remainder is:
                   1
Amount to balance against:
                   1
Error: Transaction does not balance
```

Curiouser, if I simply add a trailing whitespace to make the second posting more than one character long, like `B `, then I get what we expect,

```
$ ledger -f example.dat bal
                   1  A
                  -1  B
--------------------
                   0
```

Hmm. By the way, I would expect this to cause an error, but ledger is silent,

```
1970-01-01 example
 A  1
$ ledger -f example.dat bal
```

Version is `Ledger 3.1.3-20190331`, via `brew upgrade ledger`.

**Comment by tbm** [comment] 2020-03-20 07:52
I don't see this issue.  But I think you're reporting the same as issue #516. Can you confirm that your file didn't have an EOF and that adding that makes it work?

**Comment by bradyt** [comment] 2020-03-20 13:01
Okay, that issue has a nice reproduce format. So on my machine this is broken:

```sh
printf '1970-01-01 example\n A  1\n B' | ledger -f - bal
```

Whereas none of these are:

```sh
printf '1970-01-01 example\n A  1\n B\n' | ledger -f - bal
printf '1970-01-01 example\n A  1\n BC' | ledger -f - bal
printf '1970-01-01 example\n A  1\n B ' | ledger -f - bal
```

Note, this means we can't use the following:

```org
#+BEGIN_SRC ledger
1970-01-01 example
 A  1
 B
#+END_SRC
```

In other words, if we have

```elisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((ledger . t)))
```

Then the result of `C-c C-c` should be,

```org
#+BEGIN_SRC ledger
1970-01-01 example
 A  1
 B 
#+END_SRC

#+RESULTS:
:                    1  A
:                   -1  B
: --------------------
:                    0
```

Instead it fails very quietly. Nothing appears in echo area, but if you check the *Messages* buffer you'll see the above error there.

**Comment by bradyt** [comment] 2020-03-20 13:23
Here's another strange case:

```sh
$ printf '1970-01-01 example\n A  1\n B  0' | ledger -f - bal
                   1  A
                  -1  B
--------------------
                   0
```

And

```sh
$ printf '1970-01-01 example\n A  1\n B  -1' | ledger -f - bal
While parsing file "", line 3:
While parsing posting:
  B  -1
     ^
Error: No quantity specified for amount
```

And

```sh
$ printf '1970-01-01 example\n A  1 ¤\n B  -1 ¤' | ledger -f - bal
While parsing file "", line 3:
While parsing posting:
  B  -1 ¤
     ^^^^
Error: Invalid UTF-8 encoding for commodity name
```

Whereas, this works

```sh
$ printf '1970-01-01 example\n A  1 ¤\n B  -1 ¤0' | ledger -f - bal
                 1 ¤  A
                -1 ¤  B
--------------------
                   0
```

More strange examples,

```sh
$ printf '1970-01-01 example\n A  1 note\n B  -1 note' | ledger -f - bal
While parsing file "", line 3:
While parsing posting:
  B  -1 note
     ^^^^^^
Error: Unexpected char 'n' (Note: inline math requires parentheses)
```

```sh
$ printf '1970-01-01 example\n A  1 coin\n B  -1 coin' | ledger -f - bal
              1 coin  A
              -1 coi  B
--------------------
              -1 coi
              1 coin
```

**Comment by tbm** [comment] 2020-03-20 13:49
Sorry, I should have been clearer. When I said "I can't reproduce", this is because my editor adds a newline  automatically.

With your `printf` I can certainly reproduce.

**Comment by bradyt** [comment] 2020-03-20 14:20
And maybe we should emphasize this example, against an apparent pattern that ledger is in some sense, simply dropping a character:

```sh
$ printf '1970-01-01 example\n A  1\n BC' | ledger -f - bal
                   1  A
                  -1  BC
--------------------
                   0
```

In other words, if the file ends with an account name longer than one character, there is no issue.

**Comment by tbm** [comment] 2020-04-19 12:16
Closing as duplicate of #516

**Closed by tbm** 2020-04-19 12:16 UTC
Labels: duplicate
