### ISSUE TITLE
Build broken on boost 1.85

### ISSUE THREAD

**Issue by riastradh** [ledger/ledger#2342] opened 2024-04-28 19:46 UTC
boost 1.85 removed boost/filesystems/convenience.hpp: https://www.boost.org/users/history/version_1_85_0.html

It looks like removing this line is enough to restore the build:

https://github.com/ledger/ledger/blob/c679e3cbd5a44fa876c42b6912d9aa7729427c8f/src/system.hh.in#L143

**Comment by afh** [comment] 2024-04-28 19:54
Thanks for raising this, @riastradh, I'm going to close this as a duplicate of #2337. Let's continue the conversation [over there](https://github.com/ledger/ledger/pull/2337).

**Closed by afh** 2024-04-28 19:54 UTC
Labels: duplicate
