### ISSUE TITLE
Account names are not checked by --pedantic in cleared transactions, even with --explicit

### ISSUE THREAD

**Issue by cpitclaudel** [ledger/ledger#517] opened 2018-01-24 23:12 UTC
Contrast this:

```
$ printf '2017/01/01 * Stuff\n  A  $1\n  B\n' | ledger --pedantic -f - bal
                  $1  A
                 $-1  B
--------------------
                   0
```

…with this:

```
$ printf '2017/01/01 Stuff\n  A  $1\n  B\n' | ledger --pedantic -f - bal
While parsing file "", line 2:
While parsing posting:
  A  $1

Error: Unknown account 'A'
```

I think the second one is the intended one?

**Comment by cpitclaudel** [comment] 2018-01-24 23:27
Woops.  I got the wrong impression from reading the man page.  The actual manual makes it clear that cleared transactions are assumed correct (and mentions `--explicit`).

**Comment by cpitclaudel** [comment] 2018-01-24 23:43
Well, I spoke too fast:

```$ printf '2017/01/01 * Stuff\n  A  $1\n  B\n' | ledger --explicit --pedantic -f - bal
                  $1  A
                 $-1  B
--------------------
                   0

$ printf 'account A\n2017/01/01 * Stuff\n  A  $1\n  B\n' | ledger --explicit --pedantic -f - bal
While parsing file "", line 4:
While parsing posting:
  B

Error: Unknown account 'B'
```

Looks like you need at least one account line for --explicit to kick in?

**Comment by tbm** [comment] 2018-01-25 03:43
Yes, you're correct. Currently you need at least one account directive for this to work. I reported this to Bugzilla.

IIRC John agreed this is not intuitive and that it would be ok to change the current behaviour.

**Comment by tbm** [comment] 2018-03-25 08:29
Just to give an example (any `account` declaration will do):

```
account C

2017-01-01 * Stuff
  A  $1
  B
```

**Comment by tbm** [comment] 2018-03-25 08:31
Just for reference, this was originally reported in Bugzilla as BZ#771

**Comment by tbm** [comment] 2018-06-01 11:18
This is a duplicate of issue #771.

**Closed by tbm** 2018-06-01 11:18 UTC
Labels: bug, duplicate
