### ISSUE TITLE
Macports: "Error: Failed to configure ledger: boost must be installed with +python27"

### ISSUE THREAD

**Issue by paxperscientiam** [ledger/ledger#1921] opened 2020-05-31 14:18 UTC
Hello,

I've noticed a discrepancy between the instructions for building `ledger` with macports and a macports build error message.

Readme indicates ...
```
sudo port install -f cmake python37 \
     libiconv zlib gmp \
     mpfr ncurses ncursesw \
     gettext libedit boost-jam \
     boost +st+python37+icu texlive doxygen graphviz \
     texinfo lcov sloccount
```
... while macports indicates:
```
Error: Failed to configure ledger: boost must be installed with +python27
```

Do you think the macports build instructions are wrong?

**Comment by tbm** [comment] 2020-06-01 01:54
@paxperscientiam we (specifically @q3aiml) tried to update the instructions recently with our migration to Python 3 but I don't think anyone actually had macports to test.

Since you use macports, can you investigate what the right solution is.  In particular, is there a boost in macports that works with python 3?  Python 2 is no longer supported now, so it would be good to use Python 3.

Can you look into this? Thanks

**Comment by tbm** [comment] 2020-06-01 01:56
> Error: Failed to configure ledger: boost must be installed with +python27

Although that error suggests that +python27 is something ledger wants. (Note that I don't know anything about macports)

But acprep has been updated to +python37

**Comment by q3aiml** [comment] 2020-06-06 17:53
For what it's worth according to macports `python37` should be a valid `boost` variant: https://www.macports.org/ports.php?by=library&substr=boost. It's shame their error message isn't clearer. @paxperscientiam you could try upgrading macports if it isn't upgrading automatically or try explicitly disabling `python27` by adding something like `-python27` (guessing) to boost in the port install command.

**Comment by q3aiml** [comment] 2020-06-06 17:56
Oh, I think I see what you are saying. The error you provided is from something like `port install ledger`? If so I'm guessing someone needs to update https://github.com/macports/macports-ports/blob/master/finance/ledger/Portfile.

**Comment by tbm** [comment] 2020-06-15 12:06
@paxperscientiam do you think you can get the Portfile updated?

**Comment by tbm** [comment] 2020-07-08 03:50
@paxperscientiam do you think you can get the Portfile updated?

**Comment by paxperscientiam** [comment] 2020-07-12 20:18
@tbm. I'll give it a shot!

**Comment by paxperscientiam** [comment] 2020-07-13 04:56
OK, folks, I have a solution that Works for Me. In order to be sure that it will work broadly, I'm working with macports folks on narrowing down a bug on their end.

Portfile so far.

```
# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4

PortSystem          1.0
PortGroup           active_variants 1.1
PortGroup           cmake 1.1
PortGroup           github 1.0

github.setup        ledger ledger 3.2.1 v
revision            1
homepage            https://ledger-cli.org/
categories          finance

master_sites        https://github.com/ledger/ledger

description         A command-line, double-entry accounting tool.
long_description    Ledger is a powerful, double-entry accounting system that \
                    is accessed from the UNIX command-line.
license             BSD
maintainers         nomaintainer

platforms           darwin

checksums           rmd160  bd3f7d6c0f09f8438d025d16c0323a2d57d7426c \
                    sha256  3c13c844e69d9c331929066d6c8f2af5231fbd68025e181eebfbf46ffef21753 \
                    size    791116

depends_lib         port:boost \
                    port:boost-jam \
                    port:python38 \
                    port:libedit \
                    port:gmp \
                    port:mpfr \
                    port:gettext

require_active_variants boost python38 \

compiler.cxx_standard   2011

configure.args-append \
                    -DBOOST_ROOT=${prefix} \
                    -DBUILD_DOCS=OFF \
                    -DEDIT_LIB=${prefix}/lib/libedit.dylib \
                    -DEDIT_PATH=${prefix}/include \
                    -DGMP_LIB=${prefix}/lib/libgmp.dylib \
                    -DGMP_PATH=${prefix}/include \
                    -DMPFR_LIB=${prefix}/lib/libmpfr.dylib \
                    -DMPFR_PATH=${prefix}/include \
                    -DPYTHON_EXECUTABLE=${prefix}/bin/python3.7 \
                    -DUSE_PYTHON38_COMPONENT=ON \
                    -DUSE_DOXYGEN=OFF \
                    -DUSE_PYTHON=ON

configure.python ${prefix}/bin/python3.8
test.run            yes
```

**Comment by tbm** [comment] 2020-07-13 05:00
@paxperscientiam thank you!

**Comment by paxperscientiam** [comment] 2020-07-19 21:04
OK, looks like we've got it working. Unfortunately, I think there's still trouble with Catalina.

**Comment by tbm** [comment] 2020-07-28 03:25
Closing since the problem isn't in ledger.

**Closed** 2020-07-28 03:28 UTC
Labels: build, documentation
