### ISSUE TITLE
Only one posting with null amount allowed per transaction

### ISSUE THREAD

**Issue by avinash311** [ledger/ledger#1812] opened 2019-07-22 18:13 UTC
;; While parsing file "test.txt", line 11:
;; Error: Only one posting with null amount allowed per transaction

Using:
ledger --version
Ledger 3.1.2-20190205, the command-line accounting tool

bal or reg reports fail.

Not sure if this is the same as the issue reported in 2010:
Resetting a balance causes an error if it would do nothing. / Allow multiple null amounts if the rest have balance assignments. (BZ#436) [#1508](https://github.com/ledger/ledger/issues/1508)

[test.txt](https://github.com/ledger/ledger/files/3418690/test.txt)

**Comment by corpulentcoffee** [comment] 2019-08-01 01:25
FWIW, if you want a quick workaround for your specific use case, you might be able to use a value expression rather than a balance assignment, e.g. `($800 - account.a)` rather than `= $800`, to accomplish the same effect.

**Comment by MisterY** [comment] 2019-11-26 08:23
Shouldn't your balance statement "= $800" be on the line where the last change was made on that account (2019.07.13) and not standing on its own?

**Comment by corpulentcoffee** [comment] 2019-11-26 15:57
Ledger has [balance assertions](https://www.ledger-cli.org/3.0/doc/ledger3.html#Balance-assertions) but it *also* allows you to [reset a balance](https://www.ledger-cli.org/3.0/doc/ledger3.html#Resetting-a-balance) and send whatever the counterbalance amount is to some other account.

The docs use the example of an equity account being the balancing account, but there are other reasons one might want to do this, e.g. a future-dated entry that intends to fully-pay some credit cards but you don't yet know what their balances are going to be:

```ledger
2020-01-15 card payment
  Credit Card A  = $0
  Credit Card B  = $0
  Checking
```

Here, the bug would trigger if `Credit Card A` happens to *already* be zeroed out, and Ledger would complain that there are multiple "null" postings (i.e. `Credit Card A` and `Checking`).

Luckily, Ledger also supports expression amounts, which don't seem to suffer from this bug but do accomplish the same goal, e.g.:

```ledger
2020-01-15 card payment
  Credit Card A  (-account.amount)
  Credit Card B  (-account.amount)
  Checking
```

**Comment by brucer42** [comment] 2020-10-05 19:28
setting initial balance to zero exhibits this bug. Very distracting.

**Comment by Nadrieril** [comment] 2021-07-19 20:34
The workaround doesn't work for me because I also use hledger on the same files

**Comment by Nadrieril** [comment] 2021-07-19 22:13
Turns out this got fixed on master some time ago in https://github.com/ledger/ledger/commit/051e4ab1ef82c58dc9563281ec14c02fc250e20f :tada:

**Comment by captaincurrie** [comment] 2023-01-07 23:50
I am still getting this bug

Using,


    2023-01-07 Test
    	assets  = $0.00
    	expenses

We get


    >ledger -f - bal
    While parsing file "", line 3:
    Error: Only one posting with null amount allowed per transaction
    ledger: exit 1
    
    >hledger -f - bal
    --------------------
                       0  

Works as intended in `hledger` but not `ledger`
This is the same bug isn't it?

**Comment by tbm** [comment] 2023-01-07 23:59
>  This is the same bug isn't it?

Yes

It's fixed, but we need to make a new release

**Comment by tbm** [comment] 2023-01-07 23:59
> Turns out this got fixed on master some time ago in https://github.com/ledger/ledger/commit/051e4ab1ef82c58dc9563281ec14c02fc250e20f tada

Thanks for pointing this out.  Closing ticket.

We need to make a new release to ship this fix.

**Closed by tbm** 2023-01-07 23:59 UTC
